version: '3.1'

volumes:
  redis:
  postgres:

services:
  db:
    image: postgres:9.6
    ports:
      - 5428:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spreedemo_development
    volumes:
      - postgres:/var/lib/postgres/data

  in_memory_store:
    image: redis:3.2-alpine
    ports:
      - 6378:6379
    volumes:
      - redis:/var/lib/redis/data

  server_app: &server_app
    build: .
    volumes:
      - ./app:/home/www/spreedemo/app # Указываем, что директория app и vendor/assets в контейнере будут ссылаться на директории в Host OS (локальная нода). Таким образом, нам будет доступен hot reload приложения
      - ./vendor/assets:/home/www/spreedemo/vendor/assets
    tty: true
    stdin_open: true
    restart: on-failure
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: spreedemo_development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_DB: "redis://in_memory_store:6379"
      SECRET_KEY_BASE: STUB
      DEVISE_SECRET_KEY: STUB
    depends_on:
      - db
      - in_memory_store
    ports:
      - 3000:3000
    command: bundle exec rails server --binding 0.0.0.0

  server_worker_app:
    <<: *server_app
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - server_app
      - in_memory_store
    ports:
      - 3001:3000
